export type MangaBrowseCard = {
  title: string;
  coverFile?: string;
  coverSrc?: string;
  genre: "Action" | "Psychological" | "Sports" | "Drama";
  isPopular: boolean;
  author: string;
  chapters: number;
  volumes: number;
  views: string;
};

export const MANGA_BROWSE_CARDS: MangaBrowseCard[] = [
  {
    title: "Kagurabachi",
    coverFile: "Kagurabachi.jpg",
    genre: "Action",
    isPopular: true,
    author: "Takeru Hokazono",
    chapters: 41,
    volumes: 5,
    views: "1.2M",
  },
  {
    title: "Jujutsu Kaisen",
    coverFile: "Jujutsu Kaisen.avif",
    genre: "Action",
    isPopular: false,
    author: "Gege Akutami",
    chapters: 271,
    volumes: 30,
    views: "5.6M",
  },
  {
    title: "One Punch Man",
    coverFile: "One Punch Man.png",
    genre: "Action",
    isPopular: false,
    author: "ONE / Yusuke Murata",
    chapters: 201,
    volumes: 31,
    views: "4.3M",
  },
  {
    title: "20th Century Boys",
    coverFile: "20th Century Boys.webp",
    genre: "Psychological",
    isPopular: true,
    author: "Naoki Urasawa",
    chapters: 249,
    volumes: 22,
    views: "2.1M",
  },
  {
    title: "The Promised Neverland",
    coverFile: "The Promised Neverland.png",
    genre: "Psychological",
    isPopular: false,
    author: "Kaiu Shirai",
    chapters: 181,
    volumes: 20,
    views: "2.9M",
  },
  {
    title: "Blue Lock",
    coverFile: "Blue Lock.jpeg",
    genre: "Sports",
    isPopular: true,
    author: "Muneyuki Kaneshiro",
    chapters: 305,
    volumes: 33,
    views: "4.9M",
  },
  {
    title: "Blue Period",
    coverFile: "Blue Period.png",
    genre: "Drama",
    isPopular: true,
    author: "Tsubasa Yamaguchi",
    chapters: 77,
    volumes: 16,
    views: "1.4M",
  },
  {
    title: "Akira",
    coverFile: "Akira.png",
    genre: "Drama",
    isPopular: false,
    author: "Katsuhiro Otomo",
    chapters: 120,
    volumes: 6,
    views: "1.8M",
  },
  {
    title: "Sakamoto Days",
    coverFile: "Sakamoto Days.webp",
    genre: "Action",
    isPopular: false,
    author: "Yuto Suzuki",
    chapters: 203,
    volumes: 21,
    views: "3.2M",
  },
  {
    title: "Jojos Bizzare Adventure",
    coverFile: "Jojos Bizzare Adventure.jpeg",
    genre: "Action",
    isPopular: false,
    author: "Hirohiko Araki",
    chapters: 957,
    volumes: 136,
    views: "6.8M",
  },
  {
    title: "Beshari Gurashi Vol. 5",
    coverSrc: "/custom-user-manga/beshari-gurashi-vol-5.jpeg",
    genre: "Drama",
    isPopular: false,
    author: "Masanori Morita",
    chapters: 42,
    volumes: 5,
    views: "340K",
  },
  {
    title: "Blue",
    coverSrc: "/custom-user-manga/blue-high-rated.jpg",
    genre: "Psychological",
    isPopular: true,
    author: "Naoki Yamamoto",
    chapters: 18,
    volumes: 2,
    views: "510K",
  },
  {
    title: "Kid I Luck",
    coverSrc: "/custom-user-manga/kid-i-luck.jpg",
    genre: "Sports",
    isPopular: true,
    author: "Yuko Osada",
    chapters: 26,
    volumes: 2,
    views: "470K",
  },
  {
    title: "Mario (One-Shot)",
    coverSrc: "/custom-user-manga/mario-one-shot.jpg",
    genre: "Action",
    isPopular: false,
    author: "Masashi Kishimoto",
    chapters: 1,
    volumes: 1,
    views: "290K",
  },
  {
    title: "School Mint",
    coverSrc: "/custom-user-manga/school-mint.jpg",
    genre: "Drama",
    isPopular: false,
    author: "PengyoPoo",
    chapters: 21,
    volumes: 3,
    views: "220K",
  },
  {
    title: "Seto Utsumi Vol. 5",
    coverSrc: "/custom-user-manga/seto-utsumi-vol-5.jpeg",
    genre: "Drama",
    isPopular: false,
    author: "Kazuya Konomoto",
    chapters: 37,
    volumes: 5,
    views: "180K",
  },
  {
    title: "Shiori Experience Vol. 9",
    coverSrc: "/custom-user-manga/shiori-experience-vol-9.jpeg",
    genre: "Drama",
    isPopular: true,
    author: "Yuko Osada",
    chapters: 72,
    volumes: 9,
    views: "610K",
  },
  {
    title: "Silent Hill F Manga",
    coverSrc: "/custom-user-manga/silent-hill-f.webp",
    genre: "Psychological",
    isPopular: true,
    author: "YotsiroYakkle261",
    chapters: 7,
    volumes: 1,
    views: "760K",
  },
];
